### ISSUE TITLE
Fancy Treeview PDF from the individual page tab

### ISSUE THREAD

**Issue by Roeljj** [JustCarmen/fancy_treeview_pdf#2]
I have installed Fancy Treeview in Modules_v3/Fancy_Treeview and it works fine:
http://www.roeljongman.nl/individual.php?pid=I7610&ged=1 

Then i installed Fancy Treevie PDF in modules_v3/Fancy_treeview_pdf and it does nothing.
There is no PDF-icon as on your site.

Any idea?

**Comment by JustCarmen** [comment]
Hi, check if the subfolder mpdf is empty. If it is, you have probably downloaded the development version instead of the [release package](https://github.com/JustCarmen/fancy_treeview_pdf/releases/download/1.7.5/fancy_treeview_pdf-1.7.5.zip). When downloading the development version you need to install the mpdf library separately from [here](https://github.com/mpdf/mpdf). The release package already contains the necessary files.

Afterwards go to control panel / modules to activate the module.

**Comment by Roeljj** [comment]
The mpdf-subfolder is **not** empty. I have downloaded the files from justcarmen.nl

**Comment by JustCarmen** [comment]
Alright. And you did activate the module in the Control Panel?

If so, can you check your error logs for any message related to this module?

**Comment by Roeljj** [comment]
Yes i did activate the module, but found no error logs.
Then i deinstalled both modules  and fully removed the files from the server.
After that i reinstalled first the fancy_treview_module and again it works fine.
The i reinstalled the fancy_treeview_pdf_module and it is does not work.
Attached the logfile concerning these installs.

Does the mpdf need any separate configuration or anything else?
![screenshot_20160918205950](https://cloud.githubusercontent.com/assets/15994766/18618292/bfec89d0-7de3-11e6-94db-54caf157d8b3.png)

**Comment by JustCarmen** [comment]
I frankly have no idea why the module is not working for you. Everything seems to be alright. Can you give me a link to a Fancy Treeview page on your website? Maybe I can get some helpfull information from firebug. If that doesn't help I probably will need access to your Control Panel to investigate this further.

**Comment by Roeljj** [comment]
In my first post there was already a link : http://www.roeljongman.nl/individual.php?pid=I7610&ged=1

**Comment by JustCarmen** [comment]
I am sorry I overlooked the link... if I had better read your message we could have solved this yesterday...

I now see the confusion. The pdf icon only appears on the full Fancy Treeview page, not on the individual page tab. You haven't set any Fancy Treeview pages yet (or maybe you have, but not visible for visitors, so I can't see them).

However, for individuals with more then 3 generations of descendants you will see a 'read more' link at the bottom of the page. Clicking on that link will bring you to the full page where the pdf icon appears:

http://www.roeljongman.nl/module.php?mod=fancy_treeview&mod_action=page&rootid=I2851&ged=1

I have entered this page by clicking the 'read more' link at this page: http://www.roeljongman.nl/individual.php?pid=I2851&ged=1

**Comment by Roeljj** [comment]
Ok so far.
I misunderstood the possibilities of the module and thought ik would generate a PDF als from the inidividual page tab.
Waht is the best way to call the module for individuals that have only 2 or 3 generations, or does it not work there at all?

**Comment by JustCarmen** [comment]
Roel, at the moment the best you can do is set up one or more default Fancy Treeview pages (control panel/ modules/ click on the fancy treeview link). People can enter these pages from the menu. At the top of the page there is a field to change the root person. You can enter any person (also ones with only 1 or 2 generations) to show their tree and to download the pdf file.

See an example at my website: hhttp://wijzijnfamilie.nl/module.php?mod=fancy_treeview&mod_action=page&rootid=i355# I have changed the default root person to show an individual with only one generation in the tree.

But your question made me think... It shouldn't be hard to implement the PDF-button at the individual pages too.  I'll take this request into the next release.

**Comment by Roeljj** [comment]
Ok Carmen, thank you so far.
I would be very glad about the implementation on the individual page, because that would be much easier to understand for visitors of that page.
