### ISSUE TITLE
Update invokes error

### ISSUE THREAD

**Issue by Roeljj** [JustCarmen/fancy_treeview_pdf#4]
The latest update invokes a error.
![screenshot_20170107171839](https://cloud.githubusercontent.com/assets/15994766/21743277/113785b6-d4ff-11e6-9daa-f3f46c025ff1.jpeg)

**Comment by JustCarmen** [comment]
Hi, my mistake. I changed the function name and moved it to the main module, but I didn't realize that the check would fail when updating the PDF-module only.

Download the [latest release of Fancy Treeview](https://github.com/JustCarmen/fancy_treeview/releases/tag/1.7.9) too. That release contains the missing function.
